### ISSUE TITLE
厉害厉害，请问我的生成出来的文字都是口口口怎么办呀

### ISSUE THREAD

**Issue by ShaoGongBra** [PrintNow/php-sorry-gif#1]
系统是centos7，是不是要安装字体什么的呀

**Comment by PrintNow** [comment]
是的，需要安装中文字体，[README.md](https://github.com/PrintNow/php-sorry-gif#centos-%E4%B8%8B%E5%AE%89%E8%A3%85-ffmpeg%E5%8C%85%E7%AE%A1%E7%90%86%E6%98%AF-yum-%E7%9A%84-linux-%E5%8F%AF%E4%BD%BF%E7%94%A8%E8%AF%A5%E5%91%BD%E4%BB%A4) 有写，或者自己Google、Baidu
