### ISSUE TITLE
特地前来观摩

### ISSUE THREAD

**Issue by lyxGh** [PrintNow/php-sorry-gif#2]
请问windows系统下可以不

**Comment by PrintNow** [comment]
可以的，安装好  `ffmpeg`，开启 `system` 函数即可（不过我使用的 PHPStudy 并没有成功，你可以试下）

**Comment by lyxGh** [comment]
我试过了，我安装了win版的ffmpeg, 我在命令行运行 相同的命令会报错

**Comment by lyxGh** [comment]
[ass @ 0000014c664e5dc0] Unable to parse option value **"laragonwwwsorrycachedagong_1522806935.ass"** as image size
    Last message repeated 1 times
[ass @ 0000014c664e5dc0] Error setting option original_size to value laragonwwwsorrycachedagong_1522806935.ass.
[Parsed_ass_0 @ 0000014c65d220c0] Error applying options to the filter.
[AVFilterGraph @ 0000014c65d22000] Error initializing filter 'ass' with args **'D:laragonwwwsorrycachedagong_1522806935.ass'**
Error reinitializing filters!
Failed to inject frame into filter network: Invalid argument
Error while processing the decoded data for stream #0:0
大概是这样的错误

**Comment by PrintNow** [comment]
你去下载新版本，应该解决了这个问题

**Comment by lyxGh** [comment]
https://gitee.com/YisenLiu/gif-win
我自己搞的windows和linux通用版。

2018-4-4 21:11 刚刚clone下来的还是 不行，我这个好像可以

**Comment by PrintNow** [comment]
emmm，其实我在回复你时，已经解决了这个问题 [大佬，win上的小问题](https://github.com/PrintNow/php-sorry-gif/issues/4)

**Comment by lyxGh** [comment]
谢谢大神！我想转到gitee,  gayhub太慢...
