### ISSUE TITLE
pop子没有生成gif

### ISSUE THREAD

**Issue by cjj7227** [PrintNow/php-sorry-gif#5]
显示生成成功，但实际404，cache目录下也没有gif，其他模板都无问题。

系统：Ubuntu 16.04

**Comment by PrintNow** [comment]
已经解决了这个问题，你下载最新版或者的 `api.php` 即可解决

**Comment by suifengv32** [comment]
我想问一下大佬，使用国外的机器选择上传到搜狗是不是上传图片到搜狗是不是非常慢，我点击生成一直显示正在生成中

**Comment by PrintNow** [comment]
有可能把，我的 gifs.ga 服务器是美国洛杉矶的，上传还 ok

**Comment by suifengv32** [comment]
我的点了等半天都一直在生成中，干脆就不用外链了

**Comment by PrintNow** [comment]
emmm
