### ISSUE TITLE
生成的图片没有任何文字是不是也是缺少字体的原因呢

### ISSUE THREAD

**Issue by suifengv32** [PrintNow/php-sorry-gif#6]

**Comment by PrintNow** [comment]
生成成功后有弹出对话框吗？
![生成成功后有弹出对话框吗？](https://i.loli.net/2018/04/10/5acc3fabbc8de.png)

**Comment by suifengv32** [comment]
已经解决了，字体库我忘记添加了，所以生成的是没有字的，抱歉打扰大佬了

**Comment by PrintNow** [comment]
可能是没有安装字体的原因，一定要安装 **中文字体** ！

**Comment by PrintNow** [comment]
好的
