### ISSUE TITLE
本地测试生成之后预览出现404

### ISSUE THREAD

**Issue by Becods** [PrintNow/php-sorry-gif#9]
测试平台:PHPStudy驱动PHP 5.5.38
问题:生成后预览和下载均出现了404的问题,经检测cache目录下无任何已生成的文件

**Comment by Becods** [comment]
安装在WWW目录,并非二级目录

**Comment by PrintNow** [comment]
我大概知道了，我本地用 PHPStudy 也和你一样，在服务器就没问题。我猜测是 PHPStudy 的配置有问题，你可以使用宝塔面板（bt.cn）搭建看看。
注：你必须仔细看完「 [使用说明](https://github.com/PrintNow/php-sorry-gif/blob/master/Usage.md) 」

**Comment by lyxGh** [comment]
![bug](https://user-images.githubusercontent.com/27914088/38996410-b9191a4a-441d-11e8-8c53-d4e923c18cf4.jpg)

**Comment by PrintNow** [comment]
@Vener-liu 请检查下 `cache` 目录的权限
